---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: cloudnative-webapp-airportdb-mds
  labels:
    tier: app
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: php
    tier: app
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cloudnative-webapp-airportdb-mds
  labels:
    tier: web
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: nginx
    tier: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: cloudnative-webapp-airportdb-mds
  labels:
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
      tier: app
  template:
    metadata:
      labels:
        app: php
        tier: app
    spec:
      containers:
      - name: php
        image: icn.ocir.io/apaccpt01/cloudnative/mysql-php:0.1
        ports:
        - containerPort: 9000
        env:
        - name: MDS_HOST
          valueFrom:
            configMapKeyRef:
              name: mds-host-configmaps
              key: mds-host
        - name: MDS_DATABASE
          valueFrom:
            secretKeyRef:
              name: mds-secret
              key: mds-database
        - name: MDS_USER
          valueFrom:
            secretKeyRef:
              name: mds-secret
              key: mds-user
        - name: MDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mds-secret
              key: mds-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: cloudnative-webapp-airportdb-mds
  labels:
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
      - name: nginx
        image: icn.ocir.io/apaccpt01/cloudnative/mysql-php-nginx:0.1
        ports:
        - containerPort: 5000
---